### ISSUE TITLE
Find a way to create a working featurebranch for all project

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#105]
it would be nice to create a featurebranch in a way that it works accross all modules

**Comment by spoenemann** [comment]
What do you mean exactly? Since we have separate repositories, you need to create a feature branch on each repo.

**Comment by meysholdt** [comment]
For each git branch that we have, a Jenkins job is create automatically. The result of the job is made available in a job-specitif maven/p2 repository. The URL follows this naming scheme:
https://geschaeftskunden.telekom.de/startseite/service/kontakt-aufnehmen/288608/kontaktformulare-hotlines.html
Furthermore, in each repository (and therefore in each job) you can configure what upstream repositories it should consume:
Example: https://github.com/eclipse/xtext-core/blob/master/gradle/upstream-repositories.gradle

This gives you the flexibility to wire together any number of feature branches. So you can have a feature branch across modules. Does this resolve the issues?

**Comment by cdietrich** [comment]
No since it does not work for the tycho part. I have to create n feature branches. I have to address upstream repo in Jenkins file. I have to patch Pom and target (both) to use upstream maven and p2 repos

Since a upstream change will impact downstream stuff I have to do this every time I do something in lib core or extras basically 

Thus it would be helpful to have a toolbox or even a one button solution that guides me with that

**Comment by meysholdt** [comment]
The only scenario where this becomes relevant for Tycho is when you want to create a feature-branch in xtext-eclipse and consume it in xtext-xtend. Do you see other scenarios?

In that scenario it should work when you register your xtext-eclipse-featurebranch-p2repo-URL in xtext-xtend's .target definition.

The Tycho build in Xtend should only consume upstream artifacts via p2. In case it still does so via maven-dependency: that's a bug. The Idea build, however, consumes maven dependencies.

We discussed cross-repo-feature-branches in the past and came to the conclusion that they should not be necessary in the very most cases and that we don't want to encourage them. That's why we didn't document this possibility in the contribution guide. What are the cases where you think this is really needed?

**Comment by cdietrich** [comment]
there is stuff like the maven plugin as well.

i had often the case that upstream changes broke downstream tests and you will never find this if you dont do the work to create n feature branches

**Comment by spoenemann** [comment]
> Thus it would be helpful to have a toolbox or even a one button solution that guides me with that

In Gradle builds we have the command line options `-PuseJenkinsSnapshots=true` and `-PupstreamBranch=master`. You can use this to switch to another upstream branch name very conveniently. Maybe we could do something similar for the Maven builds?

**Comment by cdietrich** [comment]
with gitAll and AdjustPipelines this is done
