### ISSUE TITLE
Provide release notes for 2.11

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#115]

**Comment by spoenemann** [comment]
Most of the release notes can be derived from these lists:
 * [Closed release_v2.11 issues](https://github.com/search?o=asc&q=is%3Aissue+milestone%3Arelease_v2.11+is%3Aclosed+repo%3Aeclipse%2Fxtext+repo%3Aeclipse%2Fxtext-core+repo%3Aeclipse%2Fxtext-lib+repo%3Aeclipse%2Fxtext-extras+repo%3Aeclipse%2Fxtext-eclipse+repo%3Aeclipse%2Fxtext-idea+repo%3Aeclipse%2Fxtext-web+repo%3Aeclipse%2Fxtext-maven+repo%3Aeclipse%2Fxtext-xtend&ref=searchresults&s=created&type=Issues&utf8=✓)
 * [Closed milestone_v2.11.0.beta1 issues](https://github.com/search?o=asc&q=is%3Aissue+milestone%3Amilestone_v2.11.0.beta1+is%3Aclosed+repo%3Aeclipse%2Fxtext+repo%3Aeclipse%2Fxtext-core+repo%3Aeclipse%2Fxtext-lib+repo%3Aeclipse%2Fxtext-extras+repo%3Aeclipse%2Fxtext-eclipse+repo%3Aeclipse%2Fxtext-idea+repo%3Aeclipse%2Fxtext-web+repo%3Aeclipse%2Fxtext-maven+repo%3Aeclipse%2Fxtext-xtend&ref=searchresults&s=created&type=Issues&utf8=✓)

An issue that deserves special mention is eclipse/xtext-web#6, since the solution breaks most existing users of xtext-web.

**Comment by spoenemann** [comment]
Here's the document:
https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2017-01-24-version-2-11-0.md

**Comment by spoenemann** [comment]
https://www.eclipse.org/Xtext/releasenotes.html
