### ISSUE TITLE
Wrong filtering of quickfixes offered within Xtext editor (org.eclipse.xtext.ui.editor.quickfix.XtextQuickAssistProcessor.getApplicableAnnotations(...))

### ISSUE THREAD

**Issue by maximilianost** [eclipse/xtext-core#124]
When multiple error markers providing their own quickfixes are displayed at the same line in the xtext editor only quick fixes for one of the marker are displayed in the quick fix dialog.

The expectation is, that all possible quickfixes of all markers from this line are shown.

Debugging leads to the method org.eclipse.xtext.ui.editor.quickfix.XtextQuickAssistProcessor.getApplicableAnnotations(IXtextDocument, IAnnotationModel, int)
which does a strange filtering based on text positions.

**Comment by spoenemann** [comment]
Probably needs to be solved in [xtext-eclipse](https://github.com/eclipse/xtext-eclipse).

**Comment by cdietrich** [comment]
i assume we should consider both offset and lenth in the invocation context to distinguish `Crtl/Cmd+1` and Hover Quickfix. if length is -1 we should give all quickfixes on the line, else the one at [offset, offset+length]. i dont know why this filtering was introduced at the first place. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=309939 should give some hints

**Comment by holgerschill** [comment]
We did that filtering by intention to get the same behaviour as in JDT.

**Comment by holgerschill** [comment]
For me the existing behaviour feels right. Thoughts?

**Comment by meysholdt** [comment]
No, the problem is that if there are multiple markers in the same line, only the quickfixes for the "chosen marker" are being displayed in the context menu. This makes certain quickfixes inaccessible.

**Comment by holgerschill** [comment]
They are accessible but not all together at once. That was the intention and JDT does the same. Could you elaborate what you mean by inaccessible?

**Comment by meysholdt** [comment]
By inaccessible I meant a user can't see and can't invoke the quickfix.

**Comment by spoenemann** [comment]
The problem is that the API that is responsible for filtering the quick fixes (`org.eclipse.xtext.ui.editor.quickfix.XtextQuickAssistProcessor`) does not contain any hint on whether the quick fix dialog has been invoked via shortcut (e.g. cmd+1) or by clicking the light bulb on the left side. The API is not defined by Xtext, but by JFace. If we would change the behavior to show all quick fixes that are on the same line as requested by @maximilianost, you would even get all these proposals if you explicitly set the cursor into the range of one marker and use the shortcut to get the quick fixes for it. That would be very confusing.

I can confirm that the current behavior matches that of JDT as long as the markers do not overlap. IMO this behavior makes sense and should be kept more or less as it is. I proposed some changes that mainly affect the cases when markers overlap and when the cursor is put into the range of one or more markers, see eclipse/xtext-eclipse#167.

**Comment by spoenemann** [comment]
> By inaccessible I meant a user can't see and can't invoke the quickfix.

With my change a quick fix never becomes inaccessible: if you put the cursor into the range of a marker, you will get its quick fixes.

**Comment by Bananeweizen** [comment]
Hi friends, there is yet another problem in the annotation filtering, that has not been fixed and may cause some of the confusion discussed in this issue: getApplicableAnnotations() tries to find the closest annotation for the given context position, but _removes all annotations without quickfixes_ very early during that search: https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/XtextQuickAssistProcessor.java#L207

Therefore hovering over an annotation _without_ quickfix leads to displaying the quickfix of the closest annotation _with_ quickfix. Since those 2 annotations may be completely unrelated, this behaviour is very confusing. I suggest to remove the 2 lines doing that filtering to actually return the annotation currently selected by the user, and not the "nearest with quickfix".

**Comment by spoenemann** [comment]
@Bananeweizen I'll improve that behavior in my PR.

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext-eclipse/issues/649

**Comment by spoenemann** [comment]
> replaced by eclipse/xtext-eclipse#649

These are separate issues: eclipse/xtext-core#124 is about quick fixes, eclipse/xtext-eclipse#649 is about hovers.

**Comment by cdietrich** [comment]
why did you close this then?

**Comment by spoenemann** [comment]
Because it was fixed long time ago in eclipse/xtext-eclipse#167.
