### ISSUE TITLE
Javadoc incorrect for INode#getText()

### ISSUE THREAD

**Issue by tomvdbussche** [eclipse/xtext-core#1303]
The documentation for the `getText()` method in `INode` states the returned values will never be `null`.

https://github.com/eclipse/xtext-core/blob/d9a45cfd05de3037afed498cba1029cc02bf8642/org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/INode.java#L156-L161

However looking at the implementation of `AbstractNode` it seems it is possible that `null` is returned when `getRootNode()` is `null`.

https://github.com/eclipse/xtext-core/blob/d9a45cfd05de3037afed498cba1029cc02bf8642/org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/AbstractNode.java#L151-L160

**Comment by szarnekow** [comment]
Hey Tom, why is your root node null?

**Comment by tomvdbussche** [comment]
> Hey Tom, why is your root node null?

I am not sure, it was part of a logged stacktrace but I don't know that caused the root node to be `null`.

**Comment by cdietrich** [comment]
@tomvdbussche @szarnekow  how to continue with this issue

**Comment by szarnekow** [comment]
I'd like to throw IllegalStateException and document it to be thrown if the text cannot be computed.

**Comment by tomvdbussche** [comment]
That sounds fine to me, I was just confusing to get a null value when it is explicitly stated that a null value should never be returned.

**Comment by ArneDeutsch** [comment]
I've made a short search if we (internally) use the 'null'. Most of the time we use the value without a nul check indeed, indicating that the change would be save (because a null here would most probably lead to a lot of NPEs anyway). But there are (rare) cases where we explicitely check for null (and users might do as well). Example: `org.eclipse.xtext.GrammarUtil#getTypeRefName`

```
public static String getTypeRefName(TypeRef typeRef) {
	if (typeRef.getClassifier() != null)
		return typeRef.getClassifier().getName();
	final ICompositeNode node = NodeModelUtils.getNode(typeRef);
	if (node != null) {
		final BidiIterator<INode> leafNodes = node.getAsTreeIterable().iterator();
		while (leafNodes.hasPrevious()) {
			INode previous = leafNodes.previous();
			if (previous instanceof ILeafNode && !((ILeafNode) previous).isHidden()) {
				String result = previous.getText();
				if (result != null && result.startsWith("^")) {
					result = result.substring(1);
				}
				return result;
			}
		}
	}
	return null;
}
```

At other places we just return the text through other methods that are not documented to not return null. The user might expect the null and check for it. So for me the question boild down to: In what case we return null? When does the 'parent' of an AbstractNode is null (because then we return the text as null)? All nodes without a semantic element have no parent ... seems more risky than it looks ...

**Comment by ArneDeutsch** [comment]
Comited a fix to see if tests stay green. Should we merge if so?

**Comment by ArneDeutsch** [comment]
Seems there is a dedicated test that checks that null is returned ...

```
	@Test public void testGetText_NoParent() {
		AbstractNode node = createNode();
		assertNull(node.getText());
	}

```

**Comment by ArneDeutsch** [comment]
Merged.
