### ISSUE TITLE
Move from log4j 1.2 to 2.x

### ISSUE THREAD

**Issue by stevehickman** [eclipse/xtext-core#1363]
Log4j 1.2 reached end of life in 2015. The documentation for it now appears to have gone offline. That means that developers will need to use Log4j 2.x.  Users attempting to use log4j will need to load multiple versions of log4j.  If Xtext continues to use log4j 1.2, will this cause version conflicts at some point?

**Comment by kthoms** [comment]
Eclipse projects can only use approved 3rd party libraries. These are defined in the [Eclipse Orbit](https://www.eclipse.org/orbit/) project. The current set of libraries is:
https://download.eclipse.org/tools/orbit/downloads/drops/R20191126223242/

Log4J2 is not part of that, so Xtext is not allowed to use this API.

Of course it is possible to bring up other libraries to Orbit.

For the runtime part, we only use Log4j's API. It is possible to use effectively slf4j with the log4j Bridge under the hood.

We don't feel pressure to refactor to log4j2 and would like to focus our limited capacities in more important areas. If you feel that this gets more important we are open for contributions. But first, a contribution to Orbit is required.

I don't see why the usage of log4j 1.2 would cause any conflicts. Do you?

**Comment by cdietrich** [comment]
The Problem is this:

if you mix stuff hat has log4j 1 and log4j 2 on the classpath it might lead to all kind of funny classloading explosions

to fix this there are things to consider that involve work that nobody wants to invest

- bureaucracy to be allowed to use log4j 2
- work to get in onto orbit
- commonication with all users of log4j in eclipse and coordinate all of them to switch to the new version (otherwise we would have the funny problems you see inside eclipse itself). i dont know who inside eclipse is using log4j and who is not.
- there are tons of manifests in Xtext that specify a import package version. others dont.
- i dont know if we need to change something about on how we use log4j and contribute fragments/configuration (again a lot of work to investigate)

as i am not firm with all that stuff and i am also quite busy with other stuff i dont see who could work on looking into that

@szarnekow @tivervac  any comments from your side?

**Comment by szarnekow** [comment]
This would potentially break existing products that do have a custom log4j configuration for their Xtext language. I don't think this is time well spent.

**Comment by tivervac** [comment]
I'm not sure how bad this would be for us.
We use Xtext's log4j and we do custom log4j configurations
I think we'd be able to adapt though.

**Comment by cdietrich** [comment]
see also https://www.eclipse.org/lists/cross-project-issues-dev/msg17346.html

**Comment by larsrh** [comment]
The discussion on the mailing list seems to suggest moving to slf4j. Anecdotally, I have migrated an Xtext project to using slf4j-simple, by means of:

* excluding 'log4j' from the dependencies
* adding 'org.slf4j:log4j-over-slf4j' to the classpath (runtime-only)
* adding 'org.slf4j:slf4j-simple' to the classpath (runtime-only)

It seems to work so far.

**Comment by OLibutzki** [comment]
@larsrh's solution works for plain maven/Gradle builds, but is it possible to exclude transitive dependencies in OSGi?

Context: I have a maven project which interprets my DSL at runtime and therefore depends on the runtime bundle (the one that contains the .xtext file). The maven project excludes log4j and uses the log4j2 brdige (slf4j would be possible as well). In a maven build this works as expected.

Unfortunately it's not possible to execute unit tests from Eclipse as Eclipse puts all those OSGi dependencies of the runtime bundle into the classpath. This results in a SecurityException as I have two different implementations of log4j in my classpath. One is resolved from OSGi and one is provided by my maven projects which uses the runtime bundle. I don't know how to get my unit tests to work in Eclipse again.

**Comment by HannesWell** [comment]
The latest Orbit drops contain `org.apache.logging.log4j` (log4j-2): https://download.eclipse.org/tools/orbit/downloads/drops/R20210825222808/

Furthermore Orbit contains the bundles
- `org.slf4j.apis.log4j` -- 1.7.30
- `org.slf4j.log4j` -- 1.7.2

Which both seem to be different versions of `org.slf4j:log4j-over-slf4j`, the first one is much more recent.

As long as all bundles that use log4j-1 only use `Import-Package: org.apache.log4j` and not `Require-Bundle: org.apache.log4j`, `org.slf4j.apis.log4j` could be an drop-in replacement for `org.apache.log4j` because it provides the same packages (but in another bundle) like `org.apache.log4j`. What I have seen so far luckily most plug-ins use `Import-package`. This would re-direct all log4j-1 Loggers to use slf4j.

On Maven there is also `org.apache.logging.log4j:log4j-1.2-api` which seems to be a bridge from log4j-1 to log4j-2. So it could be the same drop-in replacement to redirect to log4j-2. But I have not seen that on Orbit yet. Furthermore the question is, if you can choose, do you want to go with log4j-2 or slf4j as API? For log4j-2 at least the api and implementation are separated into own maven modules (log4j-api and log4j-core). So (theoretically) it is possible to have another bridge from log4j-2 to slf4j in an application that does not want to use the log4j implementation in the end.
But in general the bridges are tricky when used in a OSGi environment like Eclipse/Equinox that has a modular classpath. With a flat classpath dealing with those bridges is much simpler. Especially when resources (config. files) have to be found as well, which is the case for log4j-2. With this in mind I think it is easier to go with slf4j instead of log4j-2. Furthermore most of the other Eclipse projects use slf4j instead of log4j-2.

With that xtext could move to slf4j internally and could provide the bridging bundle in its fragments, so legacy client/user could should still work. If that works as hoped, the most difficult part I see at the moment could be the fragment `org.eclipse.xtext.logging` which uses `org.apache.log4j` as its host and adds an appender for log4j. This probably has to be reworked to work in conjunction with slf4j, if possible.

I want to add that I'm not experienced with loggers. I have spent some time recently to add an slf4j-binding to our Eclipse application and to redirect all logging APIs (slf4j, log4j-2, log4j-1, apache.commons.logging) to the logback-classic binding (which seems to be the default for Eclipse), so I might have missed some point. Especially the configuration topic was almost ignored by me. I assume that, if you redirect log4j-1 to slf4j and bind slf4j to logback the log4j configuration is ignored/becomes irrelevant. So advices from somebody experienced in the field are much appreciated. 

I also just noticed that xtend for example also uses `org.apache.commons.logging`.

**Comment by LordAro** [comment]
Surprisingly enough, the latest drop includes 2.15.0. https://download.eclipse.org/tools/orbit/downloads/drops/R20211213173813/

I hope this issue can be expedited, given recent CVEs? I realise log4j 1.x hasn't been implicated in this particular CVE, but it's been out of support for 6 years now

**Comment by cdietrich** [comment]
yes but  there is ZERO FUNDING for such a big task. 
so please provide a concept and prs for all repos

**Comment by szarnekow** [comment]
Given the recent indicidents with log4j 2.x, I'd say it's good that we're on a log4j version that is not affected by these and that is practically not exposing any CVEs. Practically meaning, the known security risks of log4j 1.x are only relevant in rare cases, where a SocketServer is created and kept alive, but not subject to an attack vector based on the contents of log messages.

Out of support is one thing, but out of support though zero known possible attack vectors and (due to no further changes) no risk in introducing new bugs - I'd say that's not a bad thing per se.

**Comment by rbbl-dev** [comment]
@szarnekow if I understand it correctly then the vulnerability is only exposed when log4j opens it's own SocketServer for receiving logs right?
Does that happen anywhere within xtext or can that happen with some configuration?

**Comment by cdietrich** [comment]
no we dont use socketserver. if you have custom code installed/running oder user has control over config you are lost anyway as the custom code can do everything so this is to minor concern imo.

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/2028

**Comment by szarnekow** [comment]
Closed since there is already https://github.com/eclipse/xtext/issues/2028
