### ISSUE TITLE
generateTestLanguages vs clean build

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1774]
when running

```
./gradlew clean build -PuseJenkinsSnapshots=true
./gradlew generateTestLanguages -PuseJenkinsSnapshots=true
```

Then processTestResources is not executed for the 2nd run
and the build fails

workaround

```
./gradlew generateTestLanguages -PuseJenkinsSnapshots=true --rerun-tasks
```

it looks like the output tracking for gradle does not recognize this delete
https://github.com/eclipse/xtext-core/blob/da0cd0bbaaf6909aec9dcb223a99467d41ccff63/gradle/eclipse-project-layout.gradle#L33

@oehme do you have any idea?

**Comment by cdietrich** [comment]
hmm does not seem to help.

**Comment by oehme** [comment]
That project redefines the Java sourceDirs, but not the resource dirs. So those `.xtext` files are currently considered main resources. You should align that so it's test resources.

**Comment by oehme** [comment]
Okay, so I investigated this and the problem is that this `cleanupEcoreFiles` task doesn't declare that it destroys those outputs. Why is this task there at all? Why would some of the resource files be deleted after the `test` task (but not other tasks).

If you really need this task, then rewrite it like so:

```
task cleanupEcoreFiles(type: Delete) {
  delete(fileTree(dir:sourceSets.test.output.resourcesDir, includes:['**/*.ecore','**/*.xtext']))
}
```

**Comment by cdietrich** [comment]
thx @oehme
