### ISSUE TITLE
WS terminal rule does not include unicode whitespace

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#264]
In Terminal.xtext the WS rule is defined as
```
terminal WS			: (' '|'\t'|'\r'|'\n')+;
```

Unicode defines more characters as whitespace: https://www.cs.tut.fi/~jkorpela/chars/spaces.html

So it might be useful to consider them in the WS rule, e.g. 
```
terminal WS	: (STANDARDWS| UNICODEWS)+;

terminal fragment STANDARDWS: (' '|'\t'|'\r'|'\n');

terminal fragment UNICODEWS :
'\u00A0' | 
'\u1680' |
'\u180E' |
'\u2000' |
'\u2001' |
'\u2002' |
'\u2003' |
'\u2004' |
'\u2005' |
'\u2006' |
'\u2007' |
'\u2008' |
'\u2009' |
'\u200A' |
'\u200B' |
'\u202F' |
'\u205F' |
'\u3000' |
'\uFEFF';
```

**Comment by kthoms** [comment]
see also https://bugs.eclipse.org/bugs/show_bug.cgi?id=377455

**Comment by spoenemann** [comment]
That would affect *all* languages that use Terminals. We can't do that. We might consider adding `UNICODEWS` without changing `WS`, so users can choose themselves whether they want to include the new whitespace characters, but even that could affect the syntax of languages since the lexer would behave differently.

**Comment by spoenemann** [comment]
What we could do is create an additional grammar UnicodeTerminals that includes `UNICODEWS`.

**Comment by szarnekow** [comment]
There are no plans to provide an additional UnicodeTerminals grammar since it would not be used by the framework and therefore wouldn't be thoroughly tested.
