### ISSUE TITLE
support @InjectWith on @Test methods

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#56]
In Xtext we have plenty of tests and plenty of test languages. 
Quite often a test language contains all use cases that a certain test class needs. This led to many quite large test languages, which is bad due to the heavy code footprint of each language.

Instead, it would be nicer if a test class could reuse languages from a larger selection of smaller test languages. For this, however, its necessary to choose a language per `@Test` method.

Our old infrastructure (AbstractXtextTest) did support this, too. 
See `with(SomeLang.class)` in [PartialParserTest](https://github.com/eclipse/xtext-core/blob/e1a4782403497dd27f73276c409049a3d3ecdcf9/org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/PartialParserTest.java)

Conceptually it is no problem to use a language per method because the JUnit Runner by default creates a new instance of the test class for each execution of a method.

**Comment by franzbecker** [comment]
I had a brief look into it and it seems like it's quite hard to accomplish using JUnit 4.12.

The reason is that in order to perform the injection we need the actual instance of the test. It is created in `XtextRunner.createTest()` which is missing the parameter which method it is created for. There is no other way to get hold of the instance and overwriting the entire `BlockJUnit4ClassRunner.methodBlock(FrameworkMethod)` would require a lot of copy&pasting as within it the private method `withRules(...)` is called.

JUnit 4.13 (whenever it might be released) will provide a hook for it (https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java):
```
    /**
     * Returns a new fixture to run a particular test {@code method} against.
     * Default implementation executes the no-argument {@link #createTest()} method.
     *
     * @since 4.13
     */
    protected Object createTest(FrameworkMethod method) throws Exception {
        return createTest();
    }
```

For now there might be hacky solutions that store either the created test instance or the current method in a thread-local variable ☠️. A better possibility would be to create an additional JUnit MethodRule (see this [discussion](https://github.com/junit-team/junit4/issues/793)) - which might also implement the TestRule interface. Personally I would prefer having a rule instead of a custom runner as this approach is more flexible.

**Comment by szarnekow** [comment]
There are no plans to enhance the JUnit4 based test APIs.
