### ISSUE TITLE
Lots of API Baseline errors

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-core#92]
There are lots of API baseline errors in the workspace (several hundreds), e.g., 

Description Resource    Path    Location    Type
The re-exported type org.eclipse.xtext.AbstractElement has been removed from org.eclipse.xtext.ui_2.10.0    AbstractElement.java    /org.eclipse.xtext/emf-gen/org/eclipse/xtext    line 25 Compatibility Problem

Could we simply create filters for such problems? I guess these are not considered real breakage problems, but they pollute the workspace with lots of distracting errors...

**Comment by LorenzoBettini** [comment]
I was trying to set the filters, but from what I understand the problem is in the projects of xtext-core themselves: they are not PDE projects so the API tooling will not work, and all the other projects that re-export, e.g., org.eclipse.xtext, will make the API tooling report errors on the org.eclipse.xtext.

Would it make sense to covert the projects in xtext-core, which have things that other projects re-export, plug-in projects again?

**Comment by LorenzoBettini** [comment]
I just made a try, and converted org.eclipse.xtext to a plug-in projects, but the API problems are still there... setting API filters does not help: API problems are there to stay... I wouldn't know how to fix them

**Comment by meysholdt** [comment]
What if we would not use API tooling at all (remove it from our OOMPH setup) and let Jenkins generate an API report? We're doing that here already:
https://hudson.eclipse.org/xtext/job/xtext-xtend-api-diff/lastSuccessfulBuild/artifact/output/changes.html

What are the pros and cons?
 * + local Eclipse has faster workspace build
 * + API tooling did provide false positives in the past
 * - does the API report cover all scenarios that the API tooling did consider? What about manifests?

> Would it make sense to covert the projects in xtext-core, which have things that other projects re-export, plug-in projects again?

That would mean that PDE would compute the classpath based on the MANIFEST. Currently, Buildship computes the classpath based on `build.gradle`. Which makse sense since the projects are build by gradle.

**Comment by meysholdt** [comment]
also interesting: 
https://github.com/mickaelistria/apitooling
more context: https://bugs.eclipse.org/bugs/show_bug.cgi?id=399276

**Comment by LorenzoBettini** [comment]
For sure, it would be better to remove API tooling if it is behaving like it is now ;)

Concerning the problem of classpath based on MANIFEST I agree. But I see the MANIFEST is still there, I guess because it has to be released as an Eclipse plug-in in the update site, right? So the effort of keeping MANIFEST and build.gradle in synch is there to stay?

I had seen the apitooling from Mickael, but never tried that. It does not even seem to be maintained.

The API report looks useful! But you need to have a look at that, right? It would be helpful if it provided some feedback to the job and if it provided a way to ignore problems once and for all.

**Comment by spoenemann** [comment]
👍 for getting rid of PDE API Tooling.

Yes, currently we have the uncomfortable effort of keeping the manifests in synch with the Gradle files. It is possible to generate the manifests from the Gradle configuration, but we can't do that for plugins that have already been released in the past since the generated manifests would be quite different from the original ones.

**Comment by cdietrich** [comment]
we no longer use the tooling
